apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    cloudfunctions.googleapis.com/function-id: scrape_appointments_delta
    run.googleapis.com/build-base-image: us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/python310
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: backup
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/tys-bi/gcf-artifacts/tys--bi__us--central1__scrape__appointments__delta:version_1
    run.googleapis.com/build-name: projects/38780640468/locations/us-central1/builds/5dbadcda-07fc-49c9-aad5-4cbab0c6e094
    run.googleapis.com/build-source-location: gs://gcf-v2-sources-38780640468-us-central1/scrape_appointments_delta/function-source.zip#1738043393943773
    run.googleapis.com/custom-audiences: '["https://us-central1-tys-bi.cloudfunctions.net/scrape_appointments_delta"]'
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://scrape-appointments-delta-38780640468.us-central1.run.app","https://us-central1-tys-bi.cloudfunctions.net/scrape_appointments_delta","https://scrape-appointments-delta-lelcojuugq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
    goog-cloudfunctions-runtime: python310
    goog-managed-by: cloudfunctions
  name: scrape-appointments-delta
  namespace: '38780640468'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        run.googleapis.com/base-images: '{"worker":"us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/python310"}'
        run.googleapis.com/client-name: console-cloud
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
      name: scrape-appointments-delta-00083-giq
    spec:
      containerConcurrency: 14
      containers:
      - env:
        - name: LOG_EXECUTION_ID
          value: 'true'
        image: us-central1-docker.pkg.dev/tys-bi/gcf-artifacts/tys--bi__us--central1__scrape__appointments__delta:version_1
        name: worker
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: tys-bi@tys-bi.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
