steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/tys-bi/cloud-run-source-deploy/process-homebase-files:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/tys-bi/cloud-run-source-deploy/process-homebase-files:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'process-homebase-files'
      - '--image'
      - 'us-central1-docker.pkg.dev/tys-bi/cloud-run-source-deploy/process-homebase-files:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '540s'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/tys-bi/cloud-run-source-deploy/process-homebase-files:latest'
